stages:
  - deploy

deploy:
  stage: deploy
  only:
    - release
  variables:
    IP: '127.124.187.100'
    USER: 'root'
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
    - ssh $USER@$IP "git -C home/backend pull https://$CI_DEPLOY_USER:$CI_DEPLOY_PASSWORD@gitlab.com/omisoft/blog-template-back.git"
    - ssh $USER@$IP "npm i --prefix home/backend && pm2 restart backend"